Resources:
  SanjeevEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f5ee92e2d63afc18
      AvailabilityZone: ap-south-1a
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: MyEC2InstanceName
    

